apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hpa-deployment-demo
  labels: 
    app: "HPA Deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-deployment-hpa-container
        image:  nginx:latest
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu:  "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"



