apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-db
  namespace: app-1
spec:
  serviceName: "mysql"
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306



#kubectl describe statefulset mysql-db -n app-1
#kubectl get statefulsets -n app-1
