apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-provisioning-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard-read-write-once-storage-class