apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: read-write-many-persistent-volume-claim-demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 0.5Gi
  storageClassName: manual
