apiVersion: v1
kind: Pod
metadata:
  name: pod-mounting-pvc-demo
spec:
  containers:
    - name: nginx-pod-mounting-pvc-demo
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: pod-mounting-pvc-demo
          mountPath: "/app"
  volumes:
    - name: pod-mounting-pvc-demo
      persistentVolumeClaim:
        claimName: pod-mounting-pvc-demo