apiVersion: v1
kind: PersistentVolume
metadata:
  name: pod-mounting-pvc-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data-pod-mounting"