apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-demo
spec:
  capacity:
    storage:  1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data"

