apiVersion: v1
kind: PersistentVolume
metadata:
  name: read-write-once-pv-demo
spec:
  capacity: 
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy:  Delete
  storageClassName: manual 
  hostPath:
    path:  "/mnt/data/rwo"