apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rwo-persistent-volume-claim-demo
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
  storageClassName: manual
