apiVersion: v1
kind: Pod
metadata:
  name: multi-container-probes
spec:
  containers:
    - name: frontend
      image: nginx:latest
      ports:
        - containerPort: 8080
      readinessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5  
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 20

    - name: backend
      image: nginx:latest
      ports:
        - containerPort: 9090
      startupProbe:
        httpGet:
          path: /
          port: 9090
        failureThreshold: 12
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /
          port: 9090
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /
          port: 9090
        initialDelaySeconds: 15
        periodSeconds: 20
