apiVersion: v1
kind: Pod
metadata:
  name: multi-container-probes
  namespace: app-1
spec:
  containers:
    - name: frontend
      image: nginx:latest
      ports:
        - containerPort: 80
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 15
        periodSeconds: 20

    - name: backend
      image: hashicorp/http-echo
      args:
        - "-text=Hello from backend"
        - "-listen=:8080"
      ports:
        - containerPort: 8080
      startupProbe:
        httpGet:
          path: /
          port: 8080
        failureThreshold: 30
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 20
