apiVersion: v1
kind: Pod
metadata:
  name: my-app-probes
spec:
  containers:
    - name: my-app
      image: my-app:1.0
      ports:
        - containerPort: 8080

      # Liveness Probe
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 15   # Wait 15s before first check
        periodSeconds: 20         # Run every 20s
        failureThreshold: 3       # Restart container after 3 consecutive failures

      # Readiness Probe
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 5    # Wait 5s before first check
        periodSeconds: 10         # Run every 10s
        failureThreshold: 3       # Mark pod NotReady after 3 consecutive failures
