apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-pods-role-binding
  namespace: app-1   # Important: RoleBinding is namespace-scoped
subjects:
  - kind: ServiceAccount
    name: service-account-for-roles
    namespace: app-1   # Important: specify the namespace of the SA
    apiGroup: ""        # <-- Must be empty for ServiceAccount
roleRef:
  kind: Role
  name: roles-for-viewing-pods
  apiGroup: rbac.authorization.k8s.io
