apiVersion: v1 
kind: Service
metadata:
  name: nodeport-service-demo
  namespace: app-1
spec:
  type: NodePort
  selector:
    app: nginx-deployment      
  ports:
    - port:    70              # Service port 
      targetPort:  80         # Pod container port
      nodePort: 31512