apiVersion: v1
kind: PersistentVolume
metadata:
  name: read-only-once-pv-demo
spec:
  capacity: 
    storage: 3Gi
  accessModes:
    - ReadWriteOncePod 
  persistentVolumeReclaimPolicy:  Delete
  storageClassName: manual 
  hostPath:
    path: "/mnt/data/rwop"