apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: read-write-once-persistent-volume-claim-demo
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual
