apiVersion: v1
kind: Pod
metadata: 
  name: pod-with-pvc-demo
spec:
  containers:
    - name: nginx-pod-with-pvc-demo
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name:  pod-with-pvc-volume
          mountPath: "/app/user"
          readOnly : true
  volumes: 
    - name:  pod-with-pvc-volume
      persistentVolumeClaim:
        claimName:  persistent-volume-claim-demo

      