apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim-demo
  namespace: app-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual