apiVersion: v1
kind: PersistentVolume
metadata:
  name: read-only-many-pv-demo
spec:
  capacity: 
    storage: 2Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy:  Delete
  storageClassName: manual 
  hostPath:
    path: "/mnt/data/rox"