apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readonly-many-persistent-volume-claim-demo
spec:
  accessModes: 
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
